# Generated by Django 5.1.4 on 2026-07-13 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='masterdata.section')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='masterdata.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'site', 'section'), name='uniq_user_site_section')],
            },
        ),
    ]
