# Generated by Django 5.1.4 on 2026-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersiteaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maintenance_technician',
            field=models.BooleanField(default=False, help_text='Eligible to be assigned as the artisan on a BreakdownIncident (crusher_ops).'),
        ),
    ]
