# Generated by Django 5.1.4 on 2026-07-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0002_machineassignment'),
        ('masterdata', '0001_initial'),
        ('shiftmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('shift', 'Shift'), ('day', 'Day'), ('month', 'Month')], max_length=10)),
                ('period_date', models.DateField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_targets', to='machines.machine')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_targets', to='masterdata.parameter')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_targets', to='masterdata.section')),
                ('shift_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_targets', to='shiftmgmt.shiftinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_targets', to='masterdata.site')),
            ],
            options={
                'ordering': ['-period_date', 'parameter'],
                'indexes': [models.Index(fields=['site', 'period_type', 'period_date'], name='planning_pl_site_id_350f25_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('section__isnull', False), ('machine__isnull', False), _connector='OR'), name='ck_plantarget_section_or_machine')],
            },
        ),
    ]
