# Generated by Django 5.1.4 on 2026-07-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('timezone', models.CharField(default='Africa/Harare', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'UOM',
                'verbose_name_plural': 'UOMs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('scope', models.CharField(choices=[('machine', 'Machine'), ('section', 'Section'), ('shift', 'Shift-total')], max_length=10)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('integer', 'Integer'), ('text', 'Text'), ('select', 'Select'), ('boolean', 'Boolean')], max_length=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('applicable_machine_types', models.ManyToManyField(blank=True, related_name='parameters', to='masterdata.machinetype')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_parameters', to='masterdata.section')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='masterdata.uom')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='masterdata.site'),
        ),
        migrations.CreateModel(
            name='DeliveryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_destinations', to='masterdata.site')),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrusherUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crusher_units', to='masterdata.site')),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsections', to='masterdata.section')),
            ],
            options={
                'ordering': ['section', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='masterdata.parameter')),
            ],
            options={
                'ordering': ['parameter', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('parameter', 'value'), name='uniq_parameterchoice_value')],
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['site', 'active'], name='masterdata__site_id_841425_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_section_site_code'),
        ),
        migrations.AddConstraint(
            model_name='deliverydestination',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_deliverydest_site_code'),
        ),
        migrations.AddConstraint(
            model_name='crusherunit',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_crusherunit_site_code'),
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='uniq_subsection_section_code'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'section'), ('section__isnull', False)), models.Q(('scope', 'section'), _negated=True), _connector='OR'), name='ck_parameter_section_scope_requires_section'),
        ),
    ]
