# Generated by Django 5.1.4 on 2026-07-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_historicalcrusherunit_historicaldeliverydestination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparameter',
            name='aggregation',
            field=models.CharField(choices=[('sum', 'Sum'), ('average', 'Average')], default='sum', max_length=10),
        ),
        migrations.AddField(
            model_name='parameter',
            name='aggregation',
            field=models.CharField(choices=[('sum', 'Sum'), ('average', 'Average')], default='sum', max_length=10),
        ),
    ]
