# Generated by Django 5.1.4 on 2026-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_remove_historicalproductionentry_sub_section_and_more'),
        ('machines', '0006_remove_historicalmachineassignment_sub_section_and_more'),
        ('masterdata', '0003_historicalparameter_aggregation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='parameterchoice',
            options={'ordering': ['parameter', 'label']},
        ),
        migrations.RemoveField(
            model_name='historicalparameter',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='historicalparameterchoice',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='parameterchoice',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='code',
            field=models.SlugField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='code',
            field=models.SlugField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.SlugField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSubSection',
        ),
        migrations.DeleteModel(
            name='SubSection',
        ),
    ]
