# Generated by Django 5.1.4 on 2026-07-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_remove_crusherentry_crusher_unit_and_more'),
        ('masterdata', '0004_remove_subsection_section_alter_parameter_options_and_more'),
    ]

    operations = [
        # No RemoveField ops here — both models are dropped outright by
        # DeleteModel below, and (per the identical issue hit removing
        # SubSection this session) SQLite's remake-table strategy for
        # RemoveField breaks when the model is deleted in the same
        # migration.
        migrations.DeleteModel(
            name='CrusherUnit',
        ),
        migrations.DeleteModel(
            name='HistoricalCrusherUnit',
        ),
    ]
