# Generated by Django 5.1.4 on 2026-07-13 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet_number', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('breakdown', 'Breakdown'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=15)),
                ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='masterdata.section')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='masterdata.machinetype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='masterdata.site')),
            ],
            options={
                'ordering': ['site', 'machine_type', 'fleet_number'],
                'indexes': [models.Index(fields=['site', 'status'], name='machines_ma_site_id_0e216d_idx'), models.Index(fields=['machine_type', 'site'], name='machines_ma_machine_0dbf35_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'machine_type', 'fleet_number'), name='uniq_machine_site_type_fleet')],
            },
        ),
        migrations.CreateModel(
            name='MachineTypeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualified_users', to='masterdata.machinetype')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='masterdata.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'machine_type', 'site'), name='uniq_qualification_user_type_site')],
            },
        ),
    ]
