# Generated by Django 5.1.4 on 2026-07-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('shiftmgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('handed_over', 'Handed Over')], default='active', max_length=15)),
                ('release_reason', models.TextField(blank=True)),
                ('handed_over_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_over_to', to='machines.machineassignment')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='machines.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to='masterdata.section')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to='shiftmgmt.shiftinstance')),
                ('sub_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to='masterdata.subsection')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['machine', 'status'], name='machines_ma_machine_49672f_idx'), models.Index(fields=['operator', 'status'], name='machines_ma_operato_d51cb5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('machine', 'shift_instance'), name='uniq_active_assignment_per_machine_per_shift'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('operator', 'shift_instance'), name='uniq_active_assignment_per_operator_per_shift')],
            },
        ),
    ]
