# Generated by Django 5.1.4 on 2026-07-28 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_historicalmachinetypequalification'),
        ('masterdata', '0003_historicalparameter_aggregation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machinetypequalification',
            name='uniq_qualification_user_type_site',
        ),
        migrations.AddField(
            model_name='historicalmachinetypequalification',
            name='machine',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machinetypequalification',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_operators', to='machines.machine'),
        ),
        migrations.AddConstraint(
            model_name='machinetypequalification',
            constraint=models.UniqueConstraint(fields=('user', 'machine_type', 'site', 'machine'), name='uniq_qualification_user_type_site_machine'),
        ),
    ]
