# Generated by Django 5.1.4 on 2026-07-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_machinetypequalification_uniq_qualification_user_type_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmachineassignment',
            name='sub_section',
        ),
        migrations.RemoveField(
            model_name='machineassignment',
            name='sub_section',
        ),
    ]
