# Generated by Django 5.1.4 on 2026-08-17 20:43

from django.db import migrations, models


def remap_existing_status_values(apps, schema_editor):
    """The old 4-state model's codes no longer exist in STATUS_CHOICES.
    "active" -> "operating" is a straight rename (same meaning). The old
    generic "maintenance" is split into planned/unplanned in the new
    model; existing rows default to "planned_maintenance" since that's
    the more common reason an admin would have manually flipped a
    machine into maintenance (an unplanned one would usually have gone
    through breakdown reporting instead)."""
    Machine = apps.get_model("machines", "Machine")
    Machine.objects.filter(status="active").update(status="operating")
    Machine.objects.filter(status="maintenance").update(status="planned_maintenance")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_remove_historicalmachineassignment_sub_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachine',
            name='status',
            field=models.CharField(choices=[('operating', 'Operating'), ('standby', 'Standby'), ('operational_delay', 'Operational Delay'), ('planned_maintenance', 'Planned Maintenance'), ('unplanned_maintenance', 'Unplanned Maintenance'), ('breakdown', 'Breakdown'), ('refuelling', 'Refuelling'), ('no_operator', 'No Operator'), ('weather_delay', 'Weather Delay'), ('blast_clearance', 'Blast Clearance'), ('communications_loss', 'Communications Loss'), ('unknown', 'Unknown'), ('retired', 'Retired')], default='operating', max_length=25),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('operating', 'Operating'), ('standby', 'Standby'), ('operational_delay', 'Operational Delay'), ('planned_maintenance', 'Planned Maintenance'), ('unplanned_maintenance', 'Unplanned Maintenance'), ('breakdown', 'Breakdown'), ('refuelling', 'Refuelling'), ('no_operator', 'No Operator'), ('weather_delay', 'Weather Delay'), ('blast_clearance', 'Blast Clearance'), ('communications_loss', 'Communications Loss'), ('unknown', 'Unknown'), ('retired', 'Retired')], default='operating', max_length=25),
        ),
        migrations.RunPython(remap_existing_status_values, noop_reverse),
    ]
