# Generated by Django 5.1.4 on 2026-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crusher_ops', '0003_historicalbreakdowncause_historicalchecklistitem_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='breakdowncause',
            constraint=models.UniqueConstraint(condition=models.Q(('is_other', True)), fields=('is_other',), name='uniq_breakdowncause_is_other'),
        ),
    ]
