# Generated by Django 5.1.4 on 2026-07-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crusher_ops', '0004_breakdowncause_uniq_breakdowncause_is_other'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdowncause',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='breakdowncause',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='historicalbreakdowncause',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='historicalchecklistitem',
            name='display_order',
        ),
    ]
