# Generated by Django 5.1.4 on 2026-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crusher_ops', '0005_alter_breakdowncause_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhourlychecklistentry',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlychecklistentry',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
