# Generated by Django 5.1.4 on 2026-07-13 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0002_machineassignment'),
        ('masterdata', '0001_initial'),
        ('shiftmgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('slot_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slot_start_at', models.DateTimeField(blank=True, null=True)),
                ('slot_end_at', models.DateTimeField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('flagged', 'Flagged'), ('corrected', 'Corrected'), ('approved', 'Approved')], default='submitted', max_length=15)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('import', 'Import')], default='mobile', max_length=10)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_logs', to='machines.machine')),
                ('machine_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_logs', to='machines.machineassignment')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_logs', to='masterdata.downtimereasoncode')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_logs', to='masterdata.section')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_logs', to='shiftmgmt.shiftinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_logs', to='masterdata.site')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='CrusherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('hourly', 'Hourly'), ('shift_total', 'Shift Total')], default='hourly', max_length=15)),
                ('slot_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slot_start_at', models.DateTimeField(blank=True, null=True)),
                ('slot_end_at', models.DateTimeField(blank=True, null=True)),
                ('throughput_tonnes', models.DecimalField(decimal_places=3, max_digits=14)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('flagged', 'Flagged'), ('corrected', 'Corrected'), ('approved', 'Approved')], default='submitted', max_length=15)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('import', 'Import')], default='mobile', max_length=10)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('crusher_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='masterdata.crusherunit')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crusher_entries', to='masterdata.section')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crusher_entries', to='shiftmgmt.shiftinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crusher_entries', to='masterdata.site')),
            ],
            options={
                'ordering': ['-slot_start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slot_start_at', models.DateTimeField(blank=True, null=True)),
                ('slot_end_at', models.DateTimeField(blank=True, null=True)),
                ('tonnes', models.DecimalField(decimal_places=3, max_digits=14)),
                ('trip_count', models.PositiveIntegerField(default=1)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('flagged', 'Flagged'), ('corrected', 'Corrected'), ('approved', 'Approved')], default='submitted', max_length=15)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('import', 'Import')], default='mobile', max_length=10)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('delivery_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='masterdata.deliverydestination')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_entries', to='masterdata.section')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_entries', to='shiftmgmt.shiftinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_entries', to='masterdata.site')),
            ],
            options={
                'ordering': ['-slot_start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('hourly', 'Hourly'), ('shift_total', 'Shift Total')], max_length=15)),
                ('slot_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slot_start_at', models.DateTimeField(blank=True, null=True)),
                ('slot_end_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('flagged', 'Flagged'), ('corrected', 'Corrected'), ('approved', 'Approved')], default='submitted', max_length=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('import', 'Import')], default='mobile', max_length=10)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('override_reason', models.TextField(blank=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='machines.machine')),
                ('machine_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='machines.machineassignment')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='masterdata.section')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='shiftmgmt.shiftinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='masterdata.site')),
                ('sub_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='masterdata.subsection')),
            ],
            options={
                'ordering': ['-slot_start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('breakdown_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='entries.breakdownlog')),
                ('crusher_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='entries.crusherentry')),
                ('delivery_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='entries.deliveryentry')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='masterdata.parameter')),
                ('production_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='entries.productionentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='breakdownlog',
            index=models.Index(fields=['site', 'shift_instance'], name='entries_bre_site_id_f225ed_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownlog',
            index=models.Index(fields=['machine', 'start_at'], name='entries_bre_machine_07e926_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownlog',
            index=models.Index(fields=['reason_code'], name='entries_bre_reason__728ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='crusherentry',
            index=models.Index(fields=['site', 'shift_instance'], name='entries_cru_site_id_8d6b61_idx'),
        ),
        migrations.AddConstraint(
            model_name='crusherentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'hourly')), fields=('shift_instance', 'crusher_unit', 'slot_index'), name='uniq_crusherentry_hourly_slot'),
        ),
        migrations.AddConstraint(
            model_name='crusherentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'shift_total')), fields=('shift_instance', 'crusher_unit'), name='uniq_crusherentry_shift_total'),
        ),
        migrations.AddIndex(
            model_name='deliveryentry',
            index=models.Index(fields=['site', 'shift_instance'], name='entries_del_site_id_32ed4e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['site', 'shift_instance'], name='entries_pro_site_id_8d6030_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['section', 'slot_start_at'], name='entries_pro_section_85c0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['machine', 'slot_start_at'], name='entries_pro_machine_ce1868_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['status'], name='entries_pro_status_bafbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['slot_start_at'], name='entries_pro_slot_st_76196f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'hourly')), fields=('shift_instance', 'machine', 'section', 'slot_index'), name='uniq_hourly_slot'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'shift_total')), fields=('shift_instance', 'machine', 'section'), name='uniq_shift_total'),
        ),
        migrations.AddIndex(
            model_name='parametervalue',
            index=models.Index(fields=['parameter', 'production_entry'], name='entries_par_paramet_0818b4_idx'),
        ),
        migrations.AddIndex(
            model_name='parametervalue',
            index=models.Index(condition=models.Q(('value_number__isnull', False)), fields=['parameter', 'value_number'], name='idx_paramvalue_number'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('breakdown_log__isnull', True), ('crusher_entry__isnull', True), ('delivery_entry__isnull', True), ('production_entry__isnull', False)), models.Q(('breakdown_log__isnull', True), ('crusher_entry__isnull', False), ('delivery_entry__isnull', True), ('production_entry__isnull', True)), models.Q(('breakdown_log__isnull', True), ('crusher_entry__isnull', True), ('delivery_entry__isnull', False), ('production_entry__isnull', True)), models.Q(('breakdown_log__isnull', False), ('crusher_entry__isnull', True), ('delivery_entry__isnull', True), ('production_entry__isnull', True)), _connector='OR'), name='ck_parametervalue_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(condition=models.Q(('production_entry__isnull', False)), fields=('production_entry', 'parameter'), name='uniq_parametervalue_production_entry'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(condition=models.Q(('crusher_entry__isnull', False)), fields=('crusher_entry', 'parameter'), name='uniq_parametervalue_crusher_entry'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_entry__isnull', False)), fields=('delivery_entry', 'parameter'), name='uniq_parametervalue_delivery_entry'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(condition=models.Q(('breakdown_log__isnull', False)), fields=('breakdown_log', 'parameter'), name='uniq_parametervalue_breakdown_log'),
        ),
    ]
