# Generated by Django 5.1.4 on 2026-07-22 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_historicalcrusherentry_historicaldeliveryentry'),
        ('masterdata', '0002_historicalcrusherunit_historicaldeliverydestination_and_more'),
        ('shiftmgmt', '0003_historicalshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliveryentry',
            constraint=models.UniqueConstraint(fields=('shift_instance', 'delivery_destination', 'slot_index'), name='uniq_deliveryentry_hourly_slot'),
        ),
    ]
