# Generated by Django 5.1.4 on 2026-07-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_deliveryentry_uniq_deliveryentry_hourly_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductionentry',
            name='sub_section',
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='sub_section',
        ),
    ]
