# Generated by Django 5.1.4 on 2026-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_remove_historicalproductionentry_sub_section_and_more'),
        ('masterdata', '0004_remove_subsection_section_alter_parameter_options_and_more'),
    ]

    operations = [
        # No RemoveField ops for crusherentry/historicalcrusherentry fields
        # here — both models are dropped outright by DeleteModel below, and
        # (per the identical issue hit removing SubSection this session)
        # SQLite's remake-table strategy for RemoveField breaks when the
        # model is deleted in the same migration. ParameterValue's
        # crusher_entry field is a real, surviving-model column drop, so
        # those two RemoveField ops are left as-is — but must come AFTER
        # the constraints referencing that field are dropped, since SQLite's
        # remake-table strategy needs to resolve each constraint's Q()
        # condition against the field while it still exists in the state.
        migrations.RemoveConstraint(
            model_name='parametervalue',
            name='ck_parametervalue_exactly_one_parent',
        ),
        migrations.RemoveConstraint(
            model_name='parametervalue',
            name='uniq_parametervalue_crusher_entry',
        ),
        migrations.RemoveField(
            model_name='historicalparametervalue',
            name='crusher_entry',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='crusher_entry',
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('breakdown_log__isnull', True), ('delivery_entry__isnull', True), ('production_entry__isnull', False)), models.Q(('breakdown_log__isnull', True), ('delivery_entry__isnull', False), ('production_entry__isnull', True)), models.Q(('breakdown_log__isnull', False), ('delivery_entry__isnull', True), ('production_entry__isnull', True)), _connector='OR'), name='ck_parametervalue_exactly_one_parent'),
        ),
        migrations.DeleteModel(
            name='CrusherEntry',
        ),
        migrations.DeleteModel(
            name='HistoricalCrusherEntry',
        ),
    ]
