# Generated by Django 5.1.4 on 2026-08-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_remove_crusherentry_crusher_unit_and_more'),
        ('machines', '0006_remove_historicalmachineassignment_sub_section_and_more'),
        ('masterdata', '0007_seed_lhd_machine_type'),
        ('shiftmgmt', '0003_historicalshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownlog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakdownlog',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_breakdown_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakdownlog',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakdownlog',
            name='repair_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('fixed', 'Fixed'), ('confirmed', 'Confirmed')], default='reported', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalbreakdownlog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbreakdownlog',
            name='artisan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbreakdownlog',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbreakdownlog',
            name='repair_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('fixed', 'Fixed'), ('confirmed', 'Confirmed')], default='reported', max_length=15),
        ),
        migrations.AddIndex(
            model_name='breakdownlog',
            index=models.Index(fields=['repair_status'], name='entries_bre_repair__ebd2a8_idx'),
        ),
    ]
