# Generated by Django 5.1.4 on 2026-07-13 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_length_minutes', models.PositiveIntegerField(default=60)),
                ('active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='masterdata.site')),
            ],
            options={
                'ordering': ['site', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('approved', 'Approved')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='shiftmgmt.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_instances', to='masterdata.site')),
            ],
            options={
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uniq_shift_site_name'),
        ),
        migrations.AddIndex(
            model_name='shiftinstance',
            index=models.Index(fields=['site', 'date'], name='shiftmgmt_s_site_id_101681_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftinstance',
            index=models.Index(fields=['status'], name='shiftmgmt_s_status_ce71e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftinstance',
            constraint=models.UniqueConstraint(fields=('shift', 'date'), name='uniq_shiftinstance_shift_date'),
        ),
    ]
